# Original from envoyproject/envoy:examples/front-proxy/docker-compose.yml
# Modified by Instana:
# - use instana-opentracing dockerfiles
version: '3'
services:

  server:
    image: instana/scg-capture-params-demo
    networks:
      scgmesh:
        aliases:
          - service
    environment:
      - INSTANA_DEV=1
      - INSTANA_AGENT_HOST=instana-agent
      - INSTANA_AGENT_PORT=42699
      - SERVER_PORT=8080
    expose:
      - "8080"
    ports:
      - "8080:8080"

  agent:
    image: instana/agent
    pid: "host"
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev:/dev
      - /sys:/sys
      - /var/log:/var/log
      - ./agent/configuration.yaml:/root/configuration.yaml
    networks:
      scgmesh:
        aliases:
          - instana-agent
    environment:
      - INSTANA_AGENT_ENDPOINT=${agent_endpoint:?No agent endpoint provided}
      - INSTANA_AGENT_ENDPOINT_PORT=${agent_endpoint_port:-443}
      - INSTANA_AGENT_KEY=${agent_key:?No agent key provided}
      - INSTANA_AGENT_ZONE=${agent_zone:-scg-tracing-demo}
    expose:
      - "42699"

networks:
  scgmesh: {}